#!/bin/bash
# GitHub Push Script for RouteBuddy

echo "======================================"
echo "RouteBuddy GitHub Push Helper"
echo "======================================"
echo ""
echo "To push to GitHub, you need a Personal Access Token (PAT)"
echo ""
echo "How to get your token:"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token' → 'Generate new token (classic)'"
echo "3. Give it a name: 'RouteBuddy Push'"
echo "4. Select scopes: ✅ repo (full control)"
echo "5. Click 'Generate token'"
echo "6. COPY the token (you won't see it again!)"
echo ""
echo "Then run this command:"
echo ""
echo "git remote set-url origin https://YOUR_TOKEN@github.com/Jatin546/routebuddy-mobile-app.git"
echo "git push -u origin main"
echo ""
echo "Replace YOUR_TOKEN with your actual token"
echo ""
echo "======================================"
